service: virgin-active-auto-scheduler
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  cronHandler:
    handler: index.run
    environment:
      STEPHENDG: ${env:STEPHENDG}
      KATE: ${env:KATE}
      TRISTAN: ${env:TRISTAN}
    events:
      # Invoke Lambda function every day at 20:05
      - schedule: cron(5 18 * * ? *)